### PR TITLE
Hack support for @mentions

### PR DESCRIPTION
**Pull request by bkeepers**
This is a hack to ignore @mentions when checking spelling.

I don't really expect this to be merged, but wanted to start a conversation about how to extend the spellcheck module.

@wooorm any ideas?

### CODE REVIEW

**Comment by wooorm** [comment]
:+1: I’ve got an idea, hold on, I’ll check if it works!

**Comment by wooorm** [comment]
Nope. That doesn’t work. I thought if I used `remark-github`, which detects those mentions and wraps them in a link would hide them from retext, but retext is “smart” enough to still see them...

I wonder why my macOS spell checker ignores them though:
- maybe it knows about mentions but I doubt it;
- maybe, similar to how digits work in spell checkers (if there aren’t enough word-characters in a value, values are ignored as well), but I doubt that as well as it’s just one character.

Using at-mentions is pretty common, so I think I’m actually ok with adding support for them, through an option, like this. Could you fix the linting issue? `"@"` > `'@'`

**Comment by bkeepers** [comment]
> Using at-mentions is pretty common, so I think I’m actually ok with adding support for them, through an option, like this.

:cool:

> Could you fix the linting issue? `"@"` > `'@'`

Done

**Comment by wooorm** [comment]
I came up with a better solution, so your style fix was unfortunately in vain! 😬

The thing I came up with, which could also work for other non-natural-language things (and I thought of this before regarding dates, not sure why I forgot it again), is to classify those differently. That‘s the `SourceNode`.

There’s a new plugin which does exactly that: [`retext-syntax-mentions`](https://github.com/wooorm/retext-syntax-mentions). You can use it by adding `.use(require(syntaxMentions'))` somewhere before `.use(spell)`.

**Pull request closed without merging**
